### ISSUE TITLE
pyxtrlock errors out when cursor lock file not found

### ISSUE THREAD

**Issue by mattwood-okta** [leonnnn/pyxtrlock#15]
from a new install, which set PREFIX equal to /usr/local ...

```
mint@displaybox ~/src/pyxtrlock $ echo $DISPLAY
:0
mint@displaybox ~/src/pyxtrlock $ pyxtrlock
No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pyxtrlock", line 40, in <module>
    f = open(os.path.join(pyxtrlock.data_dir, "lock.pickle"), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/pyxtrlock/lock.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyxtrlock", line 43, in <module>
    panic(e.strerror)
  File "/usr/local/lib/python3.4/dist-packages/pyxtrlock/__init__.py", line 10, in panic
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyxtrlock", line 47, in <module>
    f.close()
NameError: name 'f' is not defined
```

have tried making the directory /usr/share/pyxtrlock, chgrping to mint GID, no luck. Also tried chmodding it 777, setting sticky bit, nothing seems to work. Also tried creating $HOME/.config/pyxtrlock and nothing seems to get created in that directory:.

strace doesn't seem to show any conflicts with the native system python2.7 version. Is pyxtrlock checking to see if there is no cursor lock, and if not, actually trying to create one?

**Comment by mattwood-okta** [comment]
ok I see there is a default or empty lock that is created but, it's /usr/share vs. /usr/local/share :smile: 
```
mint@displaybox ~/src/pyxtrlock $ file /usr/local/share/pyxtrlock/lock.pickle 
/usr/local/share/pyxtrlock/lock.pickle: 8086 relocatable (Microsoft)
```

So I just need to figure out what's setting the path wrong

**Comment by sebastianriese** [comment]
It is a bug/limitation in the pyxtrlock resource handling. The code assumes the install "PREFIX" to be the default Python prefix reported by `sys.prefix`. I guess this should be fixed (but I am not sure how this should be done properly).

**Comment by sirken** [comment]
A temporary workaround is to create a symbolic link:
`sudo ln -s /usr/local/share/pyxtrlock /usr/share/pyxtrlock`

**Comment by sebastianriese** [comment]
This is now fixed in devel by supplying the default lock from a python module.
