### ISSUE TITLE
"python3" hardcoded in setup.py

### ISSUE THREAD

**Issue by nils-ballmann** [leonnnn/pyxtrlock#17]
In `setup.py` the subprocess call to the python binary is hardcoded to `"python3"`:
https://github.com/leonnnn/pyxtrlock/blob/2e49b585845d624dc6dd78449a97f998683f1bda/setup.py#L15-L18

With only `python3.6` available on the system this will result in an error not being able to install pyxtrlock.

If `sys.executable` is used, the subprocess call uses the exact same python interpreter which setup.py is being called with:

        if stat_lock is None \
                or stat_lock[stat.ST_MTIME] < stat_make_lock[stat.ST_MTIME]:
            py_exec = sys.executable or "python3"
            subprocess.call([py_exec, "./make_default_lock.py"])
        super().run()

Full patch:

    diff --git a/setup.py b/setup.py
    index 0905f53..6ba3206 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -4,6 +4,7 @@ from distutils.command.install import install
     import os
     import stat
     import subprocess
    +import sys
    
     class my_install(install):
         def run(self):
    @@ -14,7 +15,8 @@ class my_install(install):
                 stat_lock = None
             if stat_lock is None \
                     or stat_lock[stat.ST_MTIME] < stat_make_lock[stat.ST_MTIME]:
    -            subprocess.call(["python3", "./make_default_lock.py"])
    +            py_exec = sys.executable or "python3"
    +            subprocess.call([py_exec, "./make_default_lock.py"])
             super().run()
    
     authors = (

**Comment by sebastianriese** [comment]
Thank you for the report. This problem no longer applies since we changed the resource handling in the development branch (the default lock is a python module now), which fixes this and other issues.
