### ISSUE TITLE
Lock keyboard but not mouse

### ISSUE THREAD

**Issue by Jogala** [leonnnn/pyxtrlock#20]
Hej guys! It would be very cool if there would be a flag, s.t. you can choose to only block the keyboard but not the mouse. 

This would be very helpful for me. I am often lying a notebook onto my keyboard when sitting on the train, watching coursera videos. Hence I need a blocked keyboard. But it would be useful to still be able to use the mouse pad for navigation purpose.

**Comment by Jogala** [comment]
Would it be enough to outcomment:

**Comment by sebastianriese** [comment]
I would recommend another solution than pyxtrlock: You only want something that grabs the keyboard an releases it on some keystrokes (e.g. Ctrl-Return) or with a mouse action (e.g. on a systray icon). No need to expose your password (especially if there's no visible feedback whether the keyboard is grabbed or not – if the cursor is not grabbed the cursor set by pyxtrlock should not be shown). You might get into the habit of typing your password to release the lock, until someday there is no keyboard lock, but your chat application is in focus.

But if you want the quick'n'dirty solution, the course of action is to comment out/remove the above lines in `./bin/pyxtrlock` *before* running `python3 setup.py install` (which implies build).

**Comment by sebastianriese** [comment]
For a possibly better solution, maybe have a look at [this askubuntu question](https://askubuntu.com/questions/160945/is-there-a-way-to-disable-a-laptops-internal-keyboard#) where methods for disabling the keyboard temporarily are discussed. [This answer](https://askubuntu.com/a/713597) might be what you are looking for and should be adaptable to other Linux distributions.
