### ISSUE TITLE
Incomplete locking when run on Wayland

### ISSUE THREAD

**Issue by javixeneize** [leonnnn/pyxtrlock#21]
Hi

I have installed pyxtrlock in a fedora laptop, and, when executing it, the browser is displayed with the padlock and i cant do anything on it, great...

But, if i hit any keyboard shortcut, or if i hit the activity bar with the mouse, i can still use the computer as normal. It looks like it only blocks the interaction of the keyboard with the browser

Am i doing something wrong? Is there any config i need to apply?

Thanks

**Comment by leonnnn** [comment]
This sounds potentially worrying. Are you running on Wayland?

Our guess is that this could happen when pyxtrlock is run on Wayland through XWayland. XWayland probably doesn’t give us enough control to securely lock the screen, so there’s likely nothing we can do to fix this. pyxtrlock would have to be reimplemented as pywtrlock, targetting Wayland platforms.

We’ll update pyxtrlock to detect whether it’s running on Wayland and fail with an error message.

**Comment by javixeneize** [comment]
Yes, we are using Wayland. It makes a lot of sense :)

Is there any way of making it compatible with Wayland?

Thanks

**Comment by leonnnn** [comment]
Unfortunately not, sorry. For wayland, a similar screen locker would have to be implemented from scratch.

To avoid giving false security impressions, we’ve released pyxtrlock 0.4 with a patch that tries to detect non-X11 sessions and refuses to run if such a session is detected.

**Comment by javixeneize** [comment]
Thanks. Happy to be of help ;)

I have seen you have submitted a cve for this. Is this a real vulnerability
in wayland or just a lack of compatibility?

**Comment by leonnnn** [comment]
It’s not a vulnerability in Wayland, pyxtrlock just is not designed to lock in a wayland session. Pyxtrlock is purely designed to lock X11 sessions.

The CVE request is for pyxtrlock giving the impression to securely lock the session, without actually doing so.
